gooutsafe/forms/login.py
import wtforms as f
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Form created to allow users to login
    """

    email = f.StringField(
        'Email',
        validators=[DataRequired()],
        id="inputEmail",
    )
    password = f.PasswordField('Password', validators=[DataRequired()])
    display = ['email', 'password']

gooutsafe/views/home.py
import json

import requests
from flask import Blueprint, flash, render_template, request
from flask_login import current_user
from gooutsafe import app
from gooutsafe.forms.restaurant_search import RestaurantSearchForm
from gooutsafe.rao.restaurant_manager import RestaurantManager 

home = Blueprint('home', __name__)


@home.route('/', methods=['GET', 'POST'])
def index():
    """General route for the index page
    """
    return render_template("index.html")


@home.route('/search', methods=['GET'])
def search():
    """This method allows customers to search restaurants, using a search bar.
    It's possible to retrieve restaurants based on their name, city or cuisine's type.

    """
    form = RestaurantSearchForm()

    keyword = request.args.get('keyword', default=None, type=str)
    filters = request.args.get('filters', default=None, type=str) or form.DEFAULT_SEARCH_FILTER
    keyword = None if keyword is None or len(keyword) == 0 else keyword
    json_list = []
    restaurants = []
    try:
        if keyword is not None:
            restaurants = search_by(keyword, filters)
        else:      
            restaurants = RestaurantManager.get_get_all()
            if not restaurants:
                flash('Error in getting all the restaurants')
            else:
                for r in restaurants:
                    json_list.append({"name": r['name'], "lat": r['lat'], "lon": r['lon'] })
            json_list = json.dumps(json_list)
    except Exception as e:
        flash('Search error')

    return render_template('explore.html', search_form=form, restaurants=restaurants, json_res=json_list)


def search_by(search_filter, search_field):
    """Implements the research of the restaurants

    Args:
        search_field (string)
        search_filter (string)

    """
    restaurants = RestaurantManager.get_search_by(search_filter, search_field)
    if restaurants is None:
        raise ValueError
    return restaurants

gooutsafe/views/restaurants.py
import requests
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from gooutsafe import app
from gooutsafe.forms.add_measure import MeasureForm
from gooutsafe.forms.add_stay_time import StayTimeForm
from gooutsafe.forms.add_table import TableForm
from gooutsafe.forms.add_times import TimesForm
from gooutsafe.forms.restaurant import RestaurantForm
from gooutsafe.rao.restaurant_manager import RestaurantManager

restaurants = Blueprint('restaurants', __name__)


@restaurants.route('/my_restaurant', methods=['GET'])
@login_required
def my_restaurant():
    """Given the operator, this method allows him to see the details of his restaurant

    Returns:
        Returns the page of the restaurant's details
    """

    return details(current_user.id)

@restaurants.route('/restaurants/<restaurant_id>')
@login_required
def restaurant_sheet(restaurant_id):
    """This method returns the single page for a restaurant

    Args:
        restaurant_id (int): univocal identifier of the restaurant
    """
    restaurant_sheet = RestaurantManager.get_restaurant_sheet(restaurant_id)
    if restaurant_sheet is None:
        flash('No restaurant found given the specified id')
        return redirect(url_for('home.index'))
        
    list_measures = restaurant_sheet['restaurant']['measures'].split(',')[1:]

    return render_template("restaurantsheet.html",
                           restaurant=restaurant_sheet['restaurant'], list_measures=list_measures,
                           average_rate=restaurant_sheet['average_rate'], max_rate=restaurant_sheet['max_rate'],
                           is_open=restaurant_sheet['is_open']
                           )


@restaurants.route('/restaurants/like/<restaurant_id>')
@login_required
def like_toggle(restaurant_id):
    """Updates the like count

    Args:
        restaurant_id (int): univocal identifier of the restaurant

    Returns:
        Redirects to the single page for a restaurant
    """
    like_toggled = RestaurantManager.put_toggle_like(restaurant_id, current_user.id)
    if not like_toggled:
        flash('Unable to toggle like')
    return restaurant_sheet(restaurant_id)


@restaurants.route('/restaurants/add/<int:id_op>', methods=['GET', 'POST'])
@login_required
def add(id_op):
    """Given an operator, this method allows him to add a restaurant

    Args:
        id_op (int): univocal identifier for the customer

    Returns:
        Redirects the view to the operator's page
    """
    form = RestaurantForm()
    if request.method == 'POST':
        if form.is_submitted():
            name = form.data['name']
            address = form.data['address']
            city = form.data['city']
            phone = form.data['phone']
            menu_type = form.data['menu_type']
            json_data_to_send = {
                'name': name,
                'address': address,
                'city': city,
                'phone': phone,
                'menu_type': menu_type,
                'op_id': id_op
            }
            restaurant_added = RestaurantManager.post_add(json_data_to_send)
            if not restaurant_added:
                flash('Something went wrong with the creation of the restaurant, sorry!')
            else:
                return redirect(url_for('auth.operator', op_id=id_op))
    return render_template('create_restaurant.html', form=form)


@restaurants.route('/restaurants/details/<int:id_op>', methods=['GET', 'POST'])
@login_required
def details(id_op):
    """Given an operator, this method allows him to see the details of his restaurant

    Args:
        id_op (int): univocal identifier of the operator

    Returns:
        Returns the page of the restaurant's details
    """
    table_form = TableForm()
    time_form = TimesForm()
    measure_form = MeasureForm()
    avg_time_form = StayTimeForm()

    json_data = RestaurantManager.get_restaurant_by_op_id(id_op)
    if not json_data:
        return redirect(url_for('restaurants.add', id_op=id_op))
    restaurant = json_data['restaurant']
    list_measures = restaurant['measures'].split(',')[1:]

    return render_template('add_restaurant_details.html',
                           restaurant=restaurant, tables=restaurant['tables'],
                           table_form=table_form, time_form=time_form,
                           times=restaurant['availabilities'], measure_form=measure_form,
                           avg_time_form=avg_time_form, avg_stay=restaurant['avg_stay'],
                           list_measure=list_measures)


@restaurants.route('/restaurants/save/<int:id_op>/<int:rest_id>', methods=['GET', 'POST'])
@login_required
def save_details(id_op, rest_id):
    """This method gives the operator the possibility to add tables to his restaurant

    Args:
        id_op (int): univocal identifier of the operator
        rest_id (int): univocal identifier of the restaurant

    Returns:
        Returns the page of the restaurant's details
    """
    table_form = TableForm()

    if request.method == "POST":
        if table_form.is_submitted():
            num_tables = table_form.data['number']
            capacity = table_form.data['max_capacity']

            json_data = {'number': num_tables, 'max_capacity': capacity}
            tables_added = RestaurantManager.post_add_tables(rest_id, json_data)
            if not tables_added:
                flash('Error in saving the tables')

    return redirect(url_for('restaurants.details', id_op=id_op))


@restaurants.route('/restaurants/savetime/<int:id_op>/<int:rest_id>', methods=['GET', 'POST'])
@login_required
def save_time(id_op, rest_id):
    """This method gives the operator the possibility to add opening hours to his restaurant

    Args:
        id_op (int): univocal identifier of the operator
        rest_id (int): univocal identifier of the restaurant

    Returns:
        Returns the page of the restaurant's details
    """
    time_form = TimesForm()
    if request.method == "POST":
        if time_form.is_submitted():
            day = time_form.data['day']
            start_time = time_form.data['start_time']
            end_time = time_form.data['end_time']

            json_data_to_send = {'day': day,
                                    'start_time': str(start_time),
                                    'end_time': str(end_time)}
            avail_added = RestaurantManager.post_add_time(rest_id, json_data_to_send) 
            if not avail_added:
                flash('Error in saving the availability')

    return redirect(url_for('restaurants.details', id_op=id_op))


@restaurants.route('/restaurants/savemeasure/<int:id_op>/<int:rest_id>', methods=['GET', 'POST'])
@login_required
def save_measure(id_op, rest_id):
    """This method gives the operator the possibility to add precaution meausures 
    to his restaurant

    Args:
        id_op (int): univocal identifier of the operator
        rest_id (int): univocal identifier of the restaurant

    Returns:
        Returns the page of the restaurant's details
    """
    measure_form = MeasureForm()

    if request.method == "POST":
        if measure_form.is_submitted():
            measure = measure_form.data['measure']
            json_data_to_send = {'measure': measure}
            measure_added = RestaurantManager.put_add_measure(rest_id, json_data_to_send)
            if not measure_added:
                flash('Error in saving the measure')
    return redirect(url_for('restaurants.details', id_op=id_op))


@restaurants.route('/restaurants/avgstay/<int:id_op>/<int:rest_id>', methods=['GET', 'POST'])
@login_required
def save_avg_stay(id_op, rest_id):
    avg_time_form = StayTimeForm()

    if request.method == "POST":
        if avg_time_form.validate_on_submit():
            hours = avg_time_form.data['hours']
            minute = avg_time_form.data['minutes']
            json_data_to_send = {'hours': hours,
                                'minutes': minute}
            avg_stay_added = RestaurantManager.put_add_avg_stay(rest_id, json_data_to_send)
            if not avg_stay_added:
                flash('Error in saving the average stay time')

    return redirect(url_for('restaurants.details', id_op=id_op))


@restaurants.route('/edit_restaurant/<int:id_op>/<int:rest_id>', methods=['GET', 'POST'])
@login_required
def edit_restaurant(id_op, rest_id):
    """This method allows the operator to edit the information about his restaurant

    Args:
        id_op (int): univocal identifier of the operator
        rest_id (int): univocal identifier of the restaurant

    Returns:
        Returns the page of the restaurant's details
    """
    form = RestaurantForm()
    if request.method == "POST":
        if form.is_submitted():
            name = form.data['name']
            address = form.data['address']
            city = form.data['city']
            phone = form.data['phone']
            menu_type = form.data['menu_type']
            json_data_to_send = {'name': name,
                                    'address': address,
                                    'city': city,
                                    'phone': phone,
                                    'menu_type': menu_type}
            restaurant_edited = RestaurantManager.put_edit_restaurant(rest_id, json_data_to_send)
            if not restaurant_edited:
                flash('Error in editing the restaurant')
            else:
                return redirect(url_for('auth.operator', op_id=id_op))

    return render_template('update_restaurant.html', form=form)

gooutsafe/views/users.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_login import (login_user, login_required, current_user, logout_user)

from gooutsafe.forms import UserForm, LoginForm
from gooutsafe.forms.update_customer import UpdateCustomerForm, AddSocialNumberForm
from gooutsafe.rao.user_manager import UserManager
from gooutsafe.auth.user import User
import requests

users = Blueprint('users', __name__)


@users.route('/create_user/<string:type_>', methods=['GET', 'POST'])
def create_user_type(type_):
    """This method allows the creation of a new user into the database

    Args:
        type_ (string): as a parameter takes a string that defines the
        type of the new user

    Returns:
        Redirects the user into his profile page, once he's logged in
    """
    form = LoginForm()
    if type_ == "customer":
        form = UserForm()

    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        
        if type_ == "operator":
            response = UserManager.create_operator(
                email,
                password
            )
        else:
            social_number = form.data['social_number']
            firstname = form.data['firstname']
            lastname = form.data['lastname']
            birthdate = form.data['birthdate']
            date = birthdate.strftime('%Y-%m-%d')
            phone = form.data['phone']
            response = UserManager.create_customer(
                'customer',
                email,
                password,
                social_number,
                firstname,
                lastname,
                date,
                phone
            )

        user = response.json()
        if user["status"] == "success":
            to_login = User.build_from_json(user["user"])
            login_user(to_login)
            if to_login.type == "operator":
                return redirect(url_for('auth.operator', op_id=to_login.id))
            else:
                return redirect(url_for('auth.profile', id=to_login.id))
        else:
            flash("Invalid credentials")
            return render_template('create_user.html', form=form, user_type=type_)
    else:
        for fieldName, errorMessages in form.errors.items():
            for errorMessage in errorMessages:
                flash('The field %s is incorrect: %s' % (fieldName, errorMessage))

    return render_template('create_user.html', form=form, user_type=type_)


@users.route('/delete_user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    """Deletes the data of the user from the database.

    Args:
        id_ (int): takes the unique id as a parameter

    Returns:
        Redirects the view to the home page
    """

    response = UserManager.delete_user(id)
    if response.status_code != 202:
        flash("Error while deleting the user")
        return redirect(url_for('auth.profile', id=id))
        
    return redirect(url_for('home.index'))


@users.route('/update_customer/<int:id>', methods=['GET', 'POST'])
@login_required
def update_customer(id):
    """This method allows the customer to edit their personal information.

    Args:
        id (int): the univocal id for the customer

    Returns:
        Redirects the view to the personal page of the customer
    """

    form = UpdateCustomerForm()
    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        phone = form.data['phone']
        searched_user = UserManager.get_user_by_email(email)
        if searched_user is not None and id != searched_user.id:
            flash("Email already present in the database.")
            return render_template('update_customer.html', form=form)

        response = UserManager.update_customer(id, email, password, phone)

        if response.status_code != 204:
            flash("Error while updating the user")
        
        return redirect(url_for('auth.profile', id=id))

    return render_template('update_customer.html', form=form)


@users.route('/update_operator/<int:id>', methods=['GET', 'POST'])
@login_required
def update_operator(id):
    """This method allows the operator to edit their personal information.

    Args:
        id (int): the univocal id for the operator

    Returns:
        Redirects the view to the personal page of the operator
    """

    form = LoginForm()
    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        searched_user = UserManager.get_user_by_email(email)
        if searched_user is not None and id != searched_user.id:
            flash("Email already present in the database.")
            return render_template('update_customer.html', form=form)

        response = UserManager.update_operator(id, email, password)

        if response.status_code != 204:
            flash("Error while updating the user")
        
        return redirect(url_for('auth.operator', op_id=id))

    return render_template('update_customer.html', form=form)


@users.route('/add_social_number/<int:id>', methods=['POST'])
@login_required
def add_social_number(id):
    """Allows the user to insert their SSN.

    Args:
        id (int): the univocal id for the user

    Returns:
        Redirects the view to the personal page of the user
    """

    social_form = AddSocialNumberForm()    
    if social_form.is_submitted():
        social_number = social_form.data['social_number']
        response = UserManager.add_social_number(id, social_number)
        
        if response.status_code != 204:
            flash("Error while updating the user")

    return redirect(url_for('auth.profile', id=id))

gooutsafe/templates/add_restaurant_details.html
{% extends "base.html" %}
{% from 'bootstrap/wtf.html' import form_field %}
{% block title %} Restaurant Management {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="float-left">
                <h1 class="display-6">Restaurant Management</h1>
            </div>
            <div class="float-right">
                <h1 class="display-5 text-primary">{{ restaurant.name }}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="lead">In this page you can <strong>add</strong> the important details to your restaurant.
                <br/>
                Please be comply with <i>COVID-19</i> rules.</p>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <h2 class="display-5 text-info">Tables</h2>
        <p class="lead">Here you can configure the tables that you can manage.</p>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>N°</th>
                    <th>Capacity</th>
                </tr>
                </thead>
                <tbody>
                {% for t in tables %}
                    <tr>
                        <td>{{ t.id }}</td>
                        <td>{{ t.capacity }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="btn-group-lg">
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#addTable">
                    Add a table
                </button>
            </div>
        </div>
        <div class="col-md-6">
            <h2 class="display-5 text-info">Opening Hours</h2>
        <p class="lead">You should configure the opening hours for your restaurant.</p>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Day</th>
                    <th>Schedule</th>
                </tr>
                </thead>
                <tbody>
                {% for t in times %}
                    <tr>
                        <td>{{ t.day }}</td>
                        <td>{{ t.start_time }} - {{ t.end_time }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="btn-group-lg">
                <!-- Button add times trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#addTimes">
                    Add times
                </button>
            </div>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <h2 class="display-5 text-danger">Precaution Measures</h2>
        <p class="lead">In this area you can configure you precaution measures.</p>

            <ul class="list-group">
                {% for m in list_measure %}
                <li class="list-group-item"> {{ m }} </li>
                {% endfor %}
            </ul>
            <div class="btn-group-lg" style="margin-top:20px">
                <!-- Button add measures trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#addMeasure">
                    Add precautions
                </button>
            </div>
        </div>
        <div class="col-md-6">
            <h2 class="display-5 text-warning">Average Stay Time</h2>
        <p class="lead">In this area you can edit the average stay time of your customers.</p>

            <ul class="list-group">
            <li class="list-group-item"> {{ avg_stay }} </li>
            </ul>
            <div class="btn-group-lg" style="margin-top:20px">
                <!-- Button add measures trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#addAvgStay">
                    Add Stay Time
                </button>
            </div>
        </div>
    </div>
    <div>
        <div class="modal fade" id="addTable" tabindex="-1"
             aria-labelledby="addTable" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addTable">Add a table</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form action="{{ url_for('restaurants.save_details', id_op=current_user.id, rest_id=restaurant.id) }}"
                              method="POST">
                            {{ table_form.hidden_tag() }}
                            {% for field in table_form.display %}
                                {{ form_field(table_form[field]) }}
                            {% endfor %}
                            <input type=submit value="Publish" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal add times -->
        <div class="modal fade" id="addTimes" tabindex="-1"
             aria-labelledby="addTimes" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addTable">Add time</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form action="{{ url_for('restaurants.save_time', id_op=current_user.id, rest_id=restaurant.id) }}"
                              method="POST">
                            {{ time_form.hidden_tag() }}
                            {% for field in time_form.display %}
                                {{ form_field(time_form[field]) }}
                            {% endfor %}

                            <input type=submit value="Publish" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal add Measures -->
        <div class="modal fade" id="addMeasure" tabindex="-1"
             aria-labelledby="addMeasure" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addTable">Add measure</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form action="{{ url_for('restaurants.save_measure', id_op=current_user.id, rest_id=restaurant.id) }}"
                              method="POST">
                            {{ measure_form.hidden_tag() }}

                            {% for field in measure_form.display %}
                                {{ form_field(measure_form[field]) }}
                            {% endfor %}
                            <input type=submit value="Publish" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="height: 50px">
    </div>

        <!-- Modal add Stay Time -->
        <div class="modal fade" id="addAvgStay" tabindex="-1"
        aria-labelledby="addAvgStay" aria-hidden="true">

           <div class="modal-dialog">
               <div class="modal-content">
                   <div class="modal-header">
                       <h5 class="modal-title" id="addTable">Add measure</h5>
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                           <span aria-hidden="true">&times;</span>
                       </button>
                   </div>

                   <div class="modal-body">
                       <form action="{{ url_for('restaurants.save_avg_stay', id_op=current_user.id, rest_id=restaurant.id) }}"
                             method="POST">
                           {{ avg_time_form.hidden_tag() }}

                           {% for field in avg_time_form.display %}
                               {{ form_field(avg_time_form[field]) }}
                           {% endfor %}
                           <input type=submit value="Publish" class="btn btn-primary">
                       </form>
                   </div>
               </div>
           </div>
       </div>
   </div>
   <div class="row" style="height: 50px">
   </div>
{% endblock %}
{% block footer %}
{% endblock %}

gooutsafe/templates/contact_tracing_positive.html
{% extends "base.html" %}

{% block title %} Authority Profile {% endblock %}

{% block content %}

    {% if current_user.is_authenticated %}
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="btn btn-outline-dark"
                        onclick="location.href='/logout'">Logout
                    </a>
                </li>
            </ul>
        </nav>
        <br>

        <h5>Hi {{current_user.name}} </h5>> <br>
        <h3>Positive Customer</h3>
                    <div>
                        <il>{{ customer.firstname }} {{ customer.lastname }} -- SSN: {{ customer.social_number }} | email: {{ customer.email }} | phone: {{ customer.phone }}</il>
                    </div>
                    <br>
        <h3>Contacts of the positive customer</h3>
        {% if pos_contact|length != 0 %}
            {% for i in range(pos_contact|length) %}
                <div>
                    <ul>
                        <li>
                            {{ pos_contact[i].firstname }} {{ pos_contact[i].lastname }} -- SSN: {{ pos_contact[i].social_number }} | email: {{ pos_contact[i].email }} | phone: {{ pos_contact[i].phone }} -- Restaurant: {{res_contact[i]}} -- Date: {{date_contact[i]}}
                        </li>
                    </ul>
                </div>  
            {% endfor %}
        {% else %}
                No contacts!
        {% endif %}
    {% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

gooutsafe/templates/create_user.html
{% extends "base.html" %}
{% from 'bootstrap/wtf.html' import form_field %}

{% block title %} Sign up {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Sign up</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {{ form.hidden_tag() }}

                {% for field in form.display %}
                    {{ form_field(form[field]) }}
                {% endfor %}
                <input type=submit value="Signup" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-4">
            {% if user_type == 'customer' %}
                <p class="lead">Are you a restaurant operator? <a
                        href="{{ url_for('users.create_user_type', type_='operator') }}">Switch the form</a></p>
            {% else %}
                <p class="lead">Are you a simple customer? <a
                        href="{{ url_for('users.create_user_type', type_='customer') }}">Switch the form</a></p>
            {% endif %}
        </div>
    </div>


{% endblock %}

{% block footer %}
{% endblock %}

gooutsafe/templates/index.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">GoOutSafe</h1>
        <p class="lead">
            GoOutSafe is a restaurant booking web application that provides the 
            possibility to track Covid-19 positives and their contacts, to prevent
            the spreding of the virus.
        </p>
        <hr class="my-4">

        <p>
            <h5> A bit hungry? Let's search for some restaurants. </h5>
        <br>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('home.search') }}" 
                role="button">
                See the map!
            </a>
        </p>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

gooutsafe/templates/thank_you_review.html
{% extends "base.html" %}

{% block title %} Thank you! {% endblock %}

{% block content %}
    <div class="row" style="margin-top:50px">
        <div class="col-md-12">
            {% if already_written is defined and already_written is sameas true %}
                <div class="alert alert-warning" role="alert">
                    You have already written a review, thank you!
                </div>
            {% else %}
                <div class="alert alert-success" role="alert">
                    Review is now added! Thank you for your time!
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="float-right">
                <a href="{{ url_for('restaurants.restaurant_sheet', restaurant_id=restaurant_id) }}">Go back</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}