gooutsafe/views/auth.py
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from gooutsafe.forms import LoginForm
from gooutsafe.forms.authority import AuthorityForm
from gooutsafe.forms.filter_form import FilterForm
from gooutsafe.forms.reservation import ReservationForm
from gooutsafe.forms.update_customer import AddSocialNumberForm
from gooutsafe.rao.user_manager import UserManager
from gooutsafe.rao.restaurant_manager import RestaurantManager
from gooutsafe.rao.reservation_manager import ReservationManager
from gooutsafe.rao.notification_tracing_manager import NotificationTracingManager as ntm

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login(re=False):
    """Allows the user to log into the system

    Args:
        re (bool, optional): boolean value that describes whenever
        the user's session is new or needs to be reloaded. Defaults to False.

    Returns:
        Redirects the view to the personal page of the user
    """
    form = LoginForm()

    if form.is_submitted():
        email, password = form.data['email'], form.data['password']
        user = UserManager.authenticate_user(email, password)
        if user is None:
            # user is not authenticated
            flash('Invalid credentials')
        else:
            # user is authenticated
            login_user(user)

            if user.type == 'operator':
                return redirect(url_for('auth.operator', op_id=user.id))
            elif user.type == 'customer':
                return redirect(url_for('auth.profile', id=user.id))
            else:
                return redirect('/authority/%d/0' % user.id)

    return render_template('login.html', form=form, re_login=re)


@auth.route('/relogin')
def re_login():
    """Method that is being called after the user's session is expired.

    """
    return login(re=True)


@auth.route('/profile/<int:id>', methods=['GET', 'POST'])
@login_required
def profile(id):
    """This method allows the customer to see its personal page

    Args:
        id (int): univocal identifier of the customer

    Returns:
        Redirects the view to personal page of the customer
    """
    if current_user.id == id:
        form = ReservationForm()
        social_form = AddSocialNumberForm()

        # restaurants = RestaurantManager.retrieve_all()
        resp = ReservationManager.get_all_reservation_customer(id)
        if resp.status_code != 200:
            return render_template('customer_profile.html', social_form=social_form)

        json_response = resp.json()
        restaurants = []
        reservations = json_response['reservations']
        for res in reservations:
            # time reformat
            start_time = datetime.strptime(res['start_time'], "%Y-%m-%d %H:%M:%S")
            res['start_time'] = datetime.strftime(start_time, "%Y-%m-%d %H:%M")
            print()
            # restaurant details extraction
            rest_dict = {}
            restaurant_id = res['restaurant_id']
            _, _, details = ReservationManager.get_restaurant_detatils(restaurant_id)
            restaurant = details['restaurant']
            rest_dict['name'] = restaurant['name']
            rest_dict['address'] = restaurant['address']
            restaurants.append(rest_dict)

        return render_template('customer_profile.html',
                               reservations=reservations, restaurants=restaurants,
                               form=form, social_form=social_form)

    return redirect(url_for('home.index'))


@auth.route('/operator/<int:op_id>', methods=['GET', 'POST'])
@login_required
def operator(op_id):
    """This method allows the operator to access the page of its personal info

    Args:
        id (int): univocal identifier of the operator

    Returns:
        Redirects the view to personal page of the operator
    """
    if current_user.id == op_id:
        filter_form = FilterForm()
        json_data = RestaurantManager.get_restaurant_by_op_id(current_user.id)
        if json_data is None:
            restaurant = None
        else:
            restaurant = json_data['restaurant']

        return render_template('operator_profile.html',
                               restaurant=restaurant, filter_form=filter_form)
    return redirect(url_for('home.index'))


@auth.route('/authority/<int:id>/<int:positive_id>', methods=['GET', 'POST'])
@login_required
def authority(id, positive_id):
    """This method allows the Health Authority to see its personal page.

    Args:
        id (int): the univocal identifier for the Health Authority
        positive_id (int): the identifier of the positive user

    Returns:
        Redirects to the page of the Health Authority
    """
    if current_user.id == id:
        ha_form = AuthorityForm()
        pos_customers = UserManager.get_all_positive_customer()
        if positive_id != 0:
            search_customer = UserManager.get_user_by_id(positive_id)
        else:  # authority clicks on "Profile"
            search_customer = None
        return render_template('authority_profile.html',
                               form=ha_form, pos_customers=pos_customers,
                               search_customer=search_customer)
    return redirect(url_for('home.index'))


@auth.route('/logout')
@login_required
def logout():
    """This method allows the users to log out of the system

    Returns:
        Redirects the view to the home page
    """
    logout_user()
    return redirect(url_for('home.index'))


@auth.route('/notifications', methods=['GET'])
@login_required
def notifications():
    """Get all notifications for the user

    Returns:
        Redirects the view to the notifications page
    """
    # TODO check datetime for notification
    # get all notifications from the manager
    notifications = ntm.retrieve_by_target_user_id(user_id=current_user.id)
    processed_notification_info = []
    if current_user.type == "customer":
        for notification in notifications:
            restaurant_name = \
                RestaurantManager.get_restaurant_sheet(notification['contagion_restaurant_id'])['restaurant']['name']
            cont_datetime = datetime.fromtimestamp((notification['contagion_datetime']['$date'] / 1000)).date()
            cont_timestamp = datetime.fromtimestamp((notification['timestamp']['$date'] / 1000))
            processed_notification_info.append({"timestamp": cont_timestamp,
                                                "contagion_datetime": cont_datetime,
                                                "contagion_restaurant_name": restaurant_name})
        return render_template('customer_notifications.html', current_user=current_user,
                               notifications=processed_notification_info)
    elif current_user.type == "operator":
        for notification in notifications:
            cont_datetime = datetime.fromtimestamp((notification['contagion_datetime']['$date'] / 1000)).date()
            cont_timestamp = datetime.fromtimestamp((notification['timestamp']['$date'] / 1000))
            info = {"timestamp": cont_timestamp,
                    "contagion_datetime": cont_datetime}
            is_future = notification['timestamp']['$date'] < notification['contagion_datetime']['$date']
            info['is_future'] = is_future
            if is_future:
                customer_phone_number = UserManager.get_user_by_id(notification['positive_customer_id']).phone
                info['customer_phone_number'] = customer_phone_number
            processed_notification_info.append(info)
        return render_template('operator_notifications.html', current_user=current_user,
                               notifications=processed_notification_info)

gooutsafe/views/users.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_login import (login_user, login_required, current_user, logout_user)

from gooutsafe.forms import UserForm, LoginForm
from gooutsafe.forms.update_customer import UpdateCustomerForm, AddSocialNumberForm
from gooutsafe.rao.user_manager import UserManager
from gooutsafe.auth.user import User
import requests

users = Blueprint('users', __name__)


@users.route('/create_user/<string:type_>', methods=['GET', 'POST'])
def create_user_type(type_):
    """This method allows the creation of a new user into the database

    Args:
        type_ (string): as a parameter takes a string that defines the
        type of the new user

    Returns:
        Redirects the user into his profile page, once he's logged in
    """
    form = LoginForm()
    if type_ == "customer":
        form = UserForm()

    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        
        if type_ == "operator":
            response = UserManager.create_operator(
                email,
                password
            )
        else:
            social_number = form.data['social_number']
            firstname = form.data['firstname']
            lastname = form.data['lastname']
            birthdate = form.data['birthdate']
            date = birthdate.strftime('%Y-%m-%d')
            phone = form.data['phone']
            response = UserManager.create_customer(
                'customer',
                email,
                password,
                social_number,
                firstname,
                lastname,
                date,
                phone
            )

        user = response.json()
        if user["status"] == "success":
            to_login = User.build_from_json(user["user"])
            login_user(to_login)
            if to_login.type == "operator":
                return redirect(url_for('auth.operator', op_id=to_login.id))
            else:
                return redirect(url_for('auth.profile', id=to_login.id))
        else:
            flash("Invalid credentials")
            return render_template('create_user.html', form=form, user_type=type_)
    else:
        for fieldName, errorMessages in form.errors.items():
            for errorMessage in errorMessages:
                flash('The field %s is incorrect: %s' % (fieldName, errorMessage))

    return render_template('create_user.html', form=form, user_type=type_)


@users.route('/delete_user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    """Deletes the data of the user from the database.

    Args:
        id_ (int): takes the unique id as a parameter

    Returns:
        Redirects the view to the home page
    """

    response = UserManager.delete_user(id)
    if response.status_code != 202:
        flash("Error while deleting the user")
        return redirect(url_for('auth.profile', id=id))
        
    return redirect(url_for('home.index'))


@users.route('/update_customer/<int:id>', methods=['GET', 'POST'])
@login_required
def update_customer(id):
    """This method allows the customer to edit their personal information.

    Args:
        id (int): the univocal id for the customer

    Returns:
        Redirects the view to the personal page of the customer
    """

    form = UpdateCustomerForm()
    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        phone = form.data['phone']
        searched_user = UserManager.get_user_by_email(email)
        if searched_user is not None and id != searched_user.id:
            flash("Email already present in the database.")
            return render_template('update_customer.html', form=form)

        response = UserManager.update_customer(id, email, password, phone)

        if response.status_code != 204:
            flash("Error while updating the user")
        
        return redirect(url_for('auth.profile', id=id))

    return render_template('update_customer.html', form=form)


@users.route('/update_operator/<int:id>', methods=['GET', 'POST'])
@login_required
def update_operator(id):
    """This method allows the operator to edit their personal information.

    Args:
        id (int): the univocal id for the operator

    Returns:
        Redirects the view to the personal page of the operator
    """

    form = LoginForm()
    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        searched_user = UserManager.get_user_by_email(email)
        if searched_user is not None and id != searched_user.id:
            flash("Email already present in the database.")
            return render_template('update_customer.html', form=form)

        response = UserManager.update_operator(id, email, password)

        if response.status_code != 204:
            flash("Error while updating the user")
        
        return redirect(url_for('auth.operator', op_id=id))

    return render_template('update_customer.html', form=form)


@users.route('/add_social_number/<int:id>', methods=['POST'])
@login_required
def add_social_number(id):
    """Allows the user to insert their SSN.

    Args:
        id (int): the univocal id for the user

    Returns:
        Redirects the view to the personal page of the user
    """

    social_form = AddSocialNumberForm()    
    if social_form.is_submitted():
        social_number = social_form.data['social_number']
        response = UserManager.add_social_number(id, social_number)
        
        if response.status_code != 204:
            flash("Error while updating the user")

    return redirect(url_for('auth.profile', id=id))

gooutsafe/templates/components/navbar/anonymous_navbar.html
{% extends "components/navbar/base_navbar.html" %}
{% block navbar_links %}{# no content #}{% endblock %}
{% block navbar_profile_links %}
    <div class="btn-group">
        <a class="btn btn-info" href="{{ url_for('auth.login') }}">Login</a>
        <a class="btn btn-success" href="{{ url_for('users.create_user_type', type_="customer") }}">Sign Up</a>
    </div>
{% endblock %}

gooutsafe/templates/components/navbar/base_navbar.html
{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
        <a class="navbar-brand" href="/">GoOutSafe</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse right" id="navbarCollapse">
            {% block navbar_links %}
            {% endblock %}
        </div>
        <div class="collapse navbar-collapse right" id="navbarCollapse">
            <form class="form-inline mt-3 mt-md-0" method="GET" action="/search">
                <input class="form-control mr-sm-2" type="text" name="keyword" placeholder="Search" aria-label="Search">
                <select class="form-control mr-sm-2" name="filters">
                    <option>Name</option>
                    <option>City</option>
                    <option>Menu Type</option>
                </select>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        <div>
            {% block navbar_profile_links %}
                <a href="">Profile</a>
            {% endblock %}
        </div>
    </nav>
{% endblock %}

gooutsafe/templates/components/navbar/customer_navbar.html
{% extends "components/navbar/base_navbar.html" %}
{% block navbar_links %}{# no content #}{% endblock %}
{% block navbar_profile_links %}
    <div class="btn-group">
        <a class="btn btn-warning" href="{{ url_for('auth.logout') }}">Logout</a>
        <a class="btn btn-info" href="{{ url_for('auth.profile', id=current_user.id) }}">My Profile</a>
        <a class="btn btn-secondary" href="{{ url_for('auth.notifications') }}">Notifications</a>
    </div>
{% endblock %}

gooutsafe/templates/components/navbar/lha_navbar.html
{% extends "components/navbar/base_navbar.html" %}

{% block navbar_profile_links %}
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/"></a>
        <ul class="nav justify-content-end">
            <li class="nav-item">
                {% if current_user.type == "operator" %}
                    <a class="btn btn-outline-primary"
                        href="{{ url_for('auth.operator', op_id=current_user.id ) }}">
                        Profile
                    </a>
                {% elif current_user.type == "customer" %}
                    <a class="btn btn-outline-primary"
                        href="{{ url_for('auth.profile', id=current_user.id ) }}">
                        Profile
                    </a>
                {% elif current_user.type == "authority" %}
                    <a class="btn btn-outline-primary"
                        href="{{ url_for('auth.authority',id=current_user.id, positive_id=0 ) }}">
                        Profile
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

gooutsafe/templates/components/navbar/rest_operator_navbar.html
{% extends "components/navbar/base_navbar.html" %}

{% block navbar_links %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('restaurants.my_restaurant') }}">My Restaurant</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('reservation.my_reservations') }}">My Reservations</a>
        </li>
    </ul>
{% endblock %}
{% block navbar_profile_links %}
    <div class="btn-group">
        <a class="btn btn-warning" href="{{ url_for('auth.logout') }}">Logout</a>
        <a class="btn btn-info" href="{{ url_for('auth.operator', op_id=current_user.id) }}">My Profile</a>
        <a class="btn btn-secondary" href="{{ url_for('auth.notifications') }}">Notifications</a>
    </div>
{% endblock %}